// Create a user
POST http://localhost:5000/user
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@gmail.com",
    "password": "123456",
    "role": "admin"
}

###
// Get All User
GET http://localhost:5000/user

###
// Get Single User
GET http://localhost:5000/user/1

###
// Update a user
PATCH http://localhost:5000/user/1
Content-Type: application/json

{
    "name": "Meita",
    "email": "admin@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "admin"
}

###
// Delete a User
DELETE http://localhost:5000/user/8aee571c-10a2-45da-90aa-786d17a47c57

###
// Login
// Create a user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}

###
// Login user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/me

###
DELETE http://localhost:5000/logout

###
// Get All Barang
GET http://localhost:5000/barang

###
// Get All Peminjaman
GET http://localhost:5000/peminjaman

###
// POST Data Barang
POST http://localhost:5000/barang
Content-Type: application/json

{
    "kode": "1234",
    "name": "Komputer",
    "stok": "20",
    "deskripsi": "Bagus kualitas masih oke"
}

###
// POST Data Peminjaman
POST http://localhost:5000/peminjaman
Content-Type: application/json

{
    "barangId": "2",
    "tglPinjam": "2024-07-09",
    "tglKembali": "2024-07-10",
    "qty": "2",
    "status": "disetujui"
}

###
// Get Single Barang
GET http://localhost:5000/barang/fcb77110-a41f-4617-a9fb-c79346af25fd

###
// Get Single Peminjaman
GET http://localhost:5000/peminjaman/825fbdb0-2e56-4152-8d9f-7befb24ef9f1

###
// Update Data Barang
PATCH http://localhost:5000/barang/fcb77110-a41f-4617-a9fb-c79346af25fd
Content-Type: application/json

{
    "kode": "1256",
    "name": "Komputer",
    "stok": "20",
    "deskripsi": "Bagus kualitas"
}

###
// Delete Data Barang
DELETE http://localhost:5000/barang/fcb77110-a41f-4617-a9fb-c79346af25fd

###
// Update Data Peminjaman
PATCH http://localhost:5000/peminjaman/3
Content-Type: application/json

{
    "tglPinjam": "2024-07-09",
    "tglKembali": "2024-07-10",
    "qty": "2",
    "status": "disetujui"
}

###
// Delete Data Peminjaman
DELETE http://localhost:5000/peminjaman/3


###
// Get All Pengembalian
GET http://localhost:5000/pengembalian

###
// POST Data Pengembalian
POST http://localhost:5000/pengembalian
Content-Type: application/json

{
    "barangId": "2",
    "tgl_pinjam": "2024-07-09",
    "tgl_kembali": "2024-07-10",
    "qty": "5",
    "kondisi": "masih tetap bagus",
    "status": "Menunggu"
}

###
// Get Single Pengembalian
GET http://localhost:5000/pengembalian/de56c9af-59f4-48c4-80ee-1e58c4a39573

###
// Update Data Pengembalian
PATCH http://localhost:5000/pengembalian/de56c9af-59f4-48c4-80ee-1e58c4a39573
Content-Type: application/json

{
    "tgl_pinjam": "19/02/2020",
    "tgl_kembali": "30/02/2020",
    "qty": "2",
    "kondisi": "agak rusak",
    "status": "Menunggu"
}

###
// Delete Data Pengembalian
DELETE http://localhost:5000/pengembalian/de56c9af-59f4-48c4-80ee-1e58c4a39573

###
// patch status
PATCH http://localhost:5000/peminjaman/1/status
Content-Type: application/json

{"status": "disetujui" }